### ISSUE TITLE
homebrew needs texinfo dependency on binutils

### ISSUE THREAD

**Issue by XarkLabs** [rosco-m68k/homebrew-toolchain#12]
It appears GNU binutils > 2.37 has an issue where formula needs added:
 depends_on "texinfo"
Or it gets a "fatal" warning/error:
==> ./configure --target=m68k-elf --prefix=/usr/local/Cellar/binutils-cross-m68k/2.40
==> make
Last 15 lines from /Users/kenj/Library/Logs/Homebrew/binutils-cross-m68k/02.make:
         want to install GNU make:
         <http://www.gnu.org/software/make/>
configure: WARNING:
*** Makeinfo is too old. Info documentation will not be built.

**Comment by roscopeco** [comment]
Closing, fixed by #13 and tested.
