### ISSUE TITLE
VASM-all checksum mismatch

### ISSUE THREAD

**Issue by floresboy** [rosco-m68k/homebrew-toolchain#2]
Updating Homebrew...
==> Installing vasm-all from rosco-m68k/toolchain
==> Downloading http://sun.hasenbraten.de/vasm/release/vasm.tar.gz
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 17f0fbf559c373ec533284672915a08727730e0f470e984f2a93e945270cc6cb
  Actual: 2b7aba9b6d0a196a2ab009fbed08f10acd94da41d11d3a224cb59b2a6c2f2b41

**Comment by floresboy** [comment]
man, your fast !!

**Comment by roscopeco** [comment]
:D 

Looks like upstream changed the source zip file, this is a problem with unversioned sources I guess :( If this becomes an ongoing problem I'll probably have to raise a new ticket to address.

**Comment by roscopeco** [comment]
Thanks for the reports btw :)

**Comment by floresboy** [comment]
Just to let you know; 68010 board is working great!!! Documentation and software set is an example to the world. Thanks!!

Kamiel

**Comment by roscopeco** [comment]
Awesome, thanks for letting me know and for the kind comments :) 

Happy hacking!
Ross

**Comment by thetrebor** [comment]
Looks like it happened again:
Error: SHA256 mismatch
Expected: 2b7aba9b6d0a196a2ab009fbed08f10acd94da41d11d3a224cb59b2a6c2f2b41
  Actual: 9ae0b37bca11cae5cf00e4d47e7225737bdaec4028e4db2a501b4eca7df8639d
    File: /Users/TheTrebor/Library/Caches/Homebrew/downloads/31e078af95a73fde88e3d55dc37179f5520233a98b3f351a785b0a3f9f54f314--vasm.tar.gz
    
is there a way I can skip the sha check?

**Comment by thetrebor** [comment]
> Looks like it happened again:
> Error: SHA256 mismatch
> Expected: 2b7aba9b6d0a196a2ab009fbed08f10acd94da41d11d3a224cb59b2a6c2f2b41
> Actual: 9ae0b37bca11cae5cf00e4d47e7225737bdaec4028e4db2a501b4eca7df8639d
> File: /Users/TheTrebor/Library/Caches/Homebrew/downloads/31e078af95a73fde88e3d55dc37179f5520233a98b3f351a785b0a3f9f54f314--vasm.tar.gz
> 
> is there a way I can skip the sha check?

I just used brew edit to update the SHA key.  looks like that check might not be necessary but it's recommended.  Anyway, thanks for this tool, hoping it works to build lantronix!

**Comment by roscopeco** [comment]
Thanks for the report @thetrebor :) Reopening this to investigate alternative means this could be avoided in future.

Initial thoughts:

* Make contact with upstream and request versioning
* Maintain a local(-ish) mirror of the VASM binary distribution, pulling in upstream and fixing the SHA at the same time
* Skip SHA check (**not preferred** as this seems to be an unstable binary dist anyway)
* Something else?
