### ISSUE TITLE
Error building gcc-cross-m68k@13 on macOS Sonoma 14.3.1 

### ISSUE THREAD

**Issue by RlinkSystem** [rosco-m68k/homebrew-toolchain#20]
When I try to do:
brew install gcc-cross-m68k@13    as in your description I get:
==> make
Last 15 lines from /Users/rogerlanden/Library/Logs/Homebrew/binutils-cross-m68k/02.make:
checking whether stpcpy is declared... yes
checking for sigsetjmp... 
checking linker --as-needed support... no
configure: updating cache ./config.cache
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
make: *** [all] Error 2

I started with brew tap rosco-m68k/toolchain and then tried to install ...

Then I tried one by one ...
brew install minipro    worked fine
brew install srecord   worked fine
brew install vasm-all  worked fine

And I using a macMini with M2 cpu 
Xcode Version 15.2 (15C500b)

**Comment by roscopeco** [comment]
I cannot replicate this, it builds fine on the Apple Silicon Macs I have. Could you please post the full content of ` /Users/rogerlanden/Library/Logs/Homebrew/binutils-cross-m68k/02.make` ?

**Comment by RlinkSystem** [comment]
[02.make.log](https://github.com/rosco-m68k/homebrew-toolchain/files/14705102/02.make.log)

Hade to rename it to 02.make.log (so I could upload it)

Don't know if this is to some help 
I found a repo with script to build the gcc-toolchain "build-m68k-toolchain.sh" and this had some problem also, as it should install it was missing gmp, so I hade to manual go to gmp  and make install and then I could build the whole package.

I did get some feeling of something not in right order.
And I was building on almost new / clean homebrew.

**Comment by roscopeco** [comment]
Hmm, it shouldn’t be related to gmp, we install that as a brew dependency in the gcc formula. Although if binutils actually needs that then it could be an ordering issue I guess 🤔

looking at your log, it looks maybe related to a static libiconv not being found, which some googling suggests might be an issue with libtool.

I will investigate further and try to replicate.

**Comment by roscopeco** [comment]
Apologies for the delay getting back on this, solved upstream and fixed here by pulling in GCC 13.3.

```
brew update
brew install gcc-cross-m68k@13
```
