### ISSUE TITLE
UBUNTU 22.04 glibc issues - reinstall of toolchain

### ISSUE THREAD

**Issue by JLovr** [rosco-m68k/homebrew-toolchain#26]
Per issue with glibc error in m68k-elf-rosco-gcc execution on UBUNTU 22.04:  

m68k-elf-rosco-gcc: /home/linuxbrew/.linuxbrew/opt/glibc/lib/libc.so.6: version `GLIBC_2.36' not found (required by m68k-elf-rosco-gcc)
m68k-elf-rosco-gcc: /home/linuxbrew/.linuxbrew/opt/glibc/lib/libc.so.6: version `GLIBC_2.38' not found (required by m68k-elf-rosco-gcc)

did brew uninstall then reinstall didn't work.  Got error during config phase:

checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/rosco-m68k-toolchainA13-20241130-430529-32x5w9/rosco-m68k-toolchain-20241103161658/build-all':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by XarkLabs** [comment]
Hello,

Not sure about brew not reinstalling.  You may need to rm -rf ~/linuxbrew or similar directory to erase "state".

However, I believe the root problem is brew is not super smart about Linux dependencies (e.g.GLIBC etc.).  To get around this you need to ask it to recompile the package when it installs (vs using the pre-built file with issues).  So, once brew is "happy" again (try "brew doctor", it may help diagnose some issues) you should try this:

`brew install --build-from-source rosco-m68k-toolchain@13`

I tested this on my (slow) Linux laptop and it downloaded and rebuilt everything in about 15 minutes (and once built fresh on your system it should run there).

**Comment by XarkLabs** [comment]
Roscopeco also mentioned you may need to install these Ubuntu packages before installing brew that brew may rely on:

`sudo apt-get install curl git make gcc g++`

**Comment by JLovr** [comment]
Will try that.  Thanks

 

John

**Comment by JLovr** [comment]
Already done.  That’s how I got it to work the first time.

**Comment by roscopeco** [comment]
This turned out to be an issue with the system includes that prevented homebrew building any software. See thread here: https://discord.com/channels/698525682199822367/698527817259941970/1313312415953322065
