### ISSUE TITLE
Issues with install on Linux

### ISSUE THREAD

**Issue by roscopeco** [rosco-m68k/homebrew-toolchain#5]
Seen by Henk Gooijen, reported on discord. Replicating here to track.

Apparently there are issues when installing the brew toolchain on Linux, specifically Ubuntu 20.04LTS. Henk resolved the issues with the commands below.

This needs to be investigated, and if replicable either be fixed or alternative toolchain arrangements made for Linux users (off the top of my head, RPMs, debs? Better build instructions?)

Process Henk followed to fix:

Started again in a new fresh VM with 20 GB storage. After I installed Ubuntu 20.04LTS, the first commands were:
sudo apt install build-essential
sudo apt install curl
sudo apt install git
Now you are ready to run the awful script line "/bin/bash -----Homebrew-----/install.sh)"
[6:25 PM]
It finishes with some advice.
1) sudo apt-get install build-essential
2) configure Homebrew in your .profile
3) add Homebrew to PATH
4) brew install gcc
[6:27 PM]
1) was already done. Do 2) and 3) and then 4).
4) will take some time ... again at the end is some advice, which I followed.
- export LDFLAGS
- export CPPFLAGS
- export PKG_CONFIG_PATH
[6:30 PM]
Next is this:
brew tap rosco-m68k/toolchain
No comments here. Next is:
brew install gcc-cross-m68k@7
At the end I got a link error, and followed the advice:
- brew unlink binutils
- brew link --overwrite binutils-cross-m68k
And then ran again:
brew install gcc-cross-m68k@7
That ends successful after 64 minutes (remember, I am running all in a VM).
[6:31 PM]
Next command:
brew install vasm-all
all OK
[6:32 PM]
The I did a command, because from previous attempts it will otherwise fail to build "srecord"
- sudo cp /usr/bin/ps2pdf /usr/bin/pstopdf
[6:37 PM]
And now
brew install srecord
It will fail, because in the link it references a path that does not exist.
It want /usr/lib/gcc/x86-64-linux-gnu/4.8/../../..x86-64-linux-gnu and the subdirectory "4.8" does not exist, but instead the subdirectory "9" exists.
To solve this, do
- cd /usr/lib/gcc/x86-64-linux-gnu
- sudo mkdir 4.8
- sudo cp 9/crtbeginS.o 4.8/
- sudo cp 9/crtendS.o 4.8/
Now run again
brew install srecord
All fine now

**Comment by tingox** [comment]
on Debian 11, this worked
- install curl and srecord via apt
install brew
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
follow brew instructions to add it to PATH etc, then do
```
brew install binutils-cross-m68k
brew install vasm-m68k
brew install gcc-cross-m68k@11
```
I'm guessing that I don't need other versions of gcc, gcc11 is enough

**Comment by roscopeco** [comment]
Closing this off, linux install from brew is now tested (with Debian) in docker.
